apiVersion: v1
kind: Service
metadata:
  name: saipavank63/similarity-search
spec:
  selector:
    app: saipavank63/similarity-search
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 32000
    - protocol: TCP
      port: 8501
      targetPort: 8501
      nodePort: 32001
  type: NodePort
